### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by OMG-1617** [dx118/dynaip#3]
作者您好，您的工作给了我很大的启发，但是我有一点疑问希望您可以解答：

文中写到您是利用了各身体部位非直接获取的初始姿态p_init和头手脚的初速度v_init作为初始状态载入模型，但我考虑的情况是，如果只用6个imu做实时动捕，初始姿态和初速度应该不是像训练模型阶段那样可以直接获取的。但是这种像PIP基于学习的RNN在应对久坐的问题上又很好解释，所以如果想运用在live demo中，这种初始状态的问题您是怎么考虑的。

很期待您的解答

**Comment by OMG-1617** [comment]
还有我想请问 xsens中 imu_mask中的elbow是否代表forearm（看代码中的编号应该是forearm），但是为什么求速度的时候用的是hand。 hand和forearm的速度我都测了一下，并不影响结果

**Comment by tuantuanzuiccc** [comment]
您好，请问您解决了这个问题吗？我发现使用源码中的前向推理，使用初始姿态进行单帧推理时，大臂并不会出现运动，是否需要像PIP算法一样，为单帧推理单独构建前向推理的代码？希望能得到您的回答
